import { PiChatTeardropTextLight } from "react-icons/pi";
import { VscSend } from "react-icons/vsc";
import { RiAttachmentLine } from "react-icons/ri";
import { BsEmojiSmile } from "react-icons/bs";
import { CiLogout, CiCirclePlus } from "react-icons/ci";
import { CgProfile } from "react-icons/cg";
import { RiLogoutBoxLine } from "react-icons/ri";
import { FaRegFilePdf } from "react-icons/fa";
import { MdOutlineDownloading } from "react-icons/md";
import { IoIosMenu } from "react-icons/io";
import { RiMenu2Line } from "react-icons/ri";

export const ChatIcon = PiChatTeardropTextLight;
export const SendMsgIcon = VscSend;
export const AttachmentIcon = RiAttachmentLine;
export const EmojiPickerIcon = BsEmojiSmile;
export const LogoutIcon = CiLogout;
export const ProfileIcon = CgProfile;
export const AddIcon = CiCirclePlus;
export const ExitChatIcon = RiLogoutBoxLine;
export const FileIcon = FaRegFilePdf;
export const DownLoadIcon = MdOutlineDownloading;
export const MenuIcon = IoIosMenu;
export const OpenChat = RiMenu2Line;
